### ISSUE TITLE
Price is in Integer

### ISSUE THREAD

**Issue by digawp** [exclusive-gix/cs2102-store#18]
Should be float or 2 dp or whatever currency-friendly data type that MySQL support

**Comment by nathanajah** [comment]
Fixed (Changed the data type to Decimal(10,2))

**Comment by 9gix** [comment]
https://github.com/exclusive-gix/cs2102-store/commit/a81bd6d436d6bd01f72fd9db9f7b5de263ea25ee

Please include the reference when closing the issue
