### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by jkt001** [exclusive-gix/cs2102-store#23]
Let's say Actor A is a "crew" in Movie "ABC".
If we delete "ABC", the row in the table "crew" associating A with "ABC" should be deleted as well.

Sekarang gw ga bisa delete movie nya karena violate integrity constraint.

Mungkin pake "ON DELETE CASCADE" ??

**Comment by 9gix** [comment]
@jkt001 yes, you need `ON DELETE CASCADE` constraint in the database for most of the Foreign Key.

**Comment by 9gix** [comment]
@jkt001 I tried to delete the Multimedia from Django Admin, and the crews is also deleted.
Let me know if you could simulate the error. Closing this issue for now.

**Comment by 9gix** [comment]
@jkt001 thanks for the recommendation.
Since we are dealing with manual deletion, we need this trigger, otherwise, we will have to delete one by one.
