### ISSUE TITLE
Search Feature & Filtering Result

### ISSUE THREAD

**Issue by 9gix** [exclusive-gix/cs2102-store#24]
Search Keyword
- [x] Title
- [x] Description
- [x] Category
- [x] Crews

**Comment by nathanajah** [comment]
Any idea how to do the link to the details? It's a bit difficult since we have different links for different multimedia type (book_detail/, music_detail/, and so on)
The only idea that comes to my mind is to try every single multimedia type...

**Comment by digawp** [comment]
Yeah I am having problem when writing the `review` app due to the different names too, though I managed to overcome it, somehow lol. Maybe we should refactor it?

**Comment by 9gix** [comment]
@nathanajah What's the status of this Issue? is this done?
Should we ignore Category? 
Where is the PR.

**Comment by nathanajah** [comment]
Category should be done. #63
