### ISSUE TITLE
Upgrading Django 1.8

### ISSUE THREAD

**Issue by 9gix** [exclusive-gix/cs2102-store#40]
https://github.com/exclusive-gix/cs2102-store/pull/41

**Comment by digawp** [comment]
The timing of this release really cannot be any worse

**Comment by nathanajah** [comment]
Do we really need to upgrade?

**Comment by 9gix** [comment]
I suggest yes. Because I don't want outdated stuff. 
The only drawback is the 3rd party library which is not compatible. But so far I didn't encounter any.

So, shall we merge this?
