### ISSUE TITLE
Initial Seed Data

### ISSUE THREAD

**Issue by 9gix** [exclusive-gix/cs2102-store#5]
- [x] Seed Super User Data https://github.com/exclusive-gix/cs2102-store/issues/6
- [x] Seed Book Data (Author, Publisher, Category, MultimediaCategory, Content, MultimediaContent) @9gix https://github.com/exclusive-gix/cs2102-store/pull/12
- [x] Seed Music Data (Singer, Studio, Category, MultimediaCategory, Content, MultimediaContent) @mikelimantara  https://github.com/exclusive-gix/cs2102-store/pull/12
- [x] Seed Album Data @mikelimantara  https://github.com/exclusive-gix/cs2102-store/pull/12
- [x] Seed Application Data (Developer, Category, MultimediaCategory, Content, MultimediaContent) @jkt001 
- [x] Seed Movie Data (Producer, Director, Actor, Actress, Studio, Category, MultimediaCategory, Content, MultimediaContent)  @jkt001 
- [x] ~~Seed Review Data~~

**Comment by 9gix** [comment]
@jkt001 Please work on this one first. You can find our existing migration at https://github.com/exclusive-gix/cs2102-store/tree/master/schema

After that the django will execute the migration from the scripts at migrations subfolder of crews and multimedia.
such as:
* https://github.com/exclusive-gix/cs2102-store/blob/master/crew/migrations/0001_create_table.py
*https://github.com/exclusive-gix/cs2102-store/blob/master/multimedia/migrations/0001_create_table.py

Currently, We have 3 scripts for each apps, create schema, create model, and seed data.

You should be able to proceed from here.

**Comment by 9gix** [comment]
@jkt001 once the table created, please seed the data.

**Comment by digawp** [comment]
Need seed for review as well

**Comment by jkt001** [comment]
seeding application now... however, all apps seem to have only the "developer" listed as the organization. Should I put the same names for both fields (this seems to be the easiest resolution).
