### ISSUE TITLE
Cannot add item to cart

### ISSUE THREAD

**Issue by digawp** [exclusive-gix/cs2102-store#62]
Need to add "Add to cart" button on all detail page (and maybe list page too)

**Comment by jkt001** [comment]
btw, user yg ud beli item A, jgn bisa add item A lg ke cart... tp tulis "Purchased" (assume ud bayar)

**Comment by 9gix** [comment]
@exclusive-gix/cs2102-group-45-2014-2015-semester-2 
Anyone want to work on this ticket?

**Comment by mikelimantara** [comment]
I thought this is done? Add to cart button is implemented at the detail page. #67

**Comment by 9gix** [comment]
@mikelimantara please fix the issue mention in the PR. Things are not done when it is not in the master.

**Comment by digawp** [comment]
Closed by #74
