### ISSUE TITLE
Content table not necessary

### ISSUE THREAD

**Issue by digawp** [exclusive-gix/cs2102-store#8]
- [x] Update ERD diagram (merge content with multimedia_content)

**Comment by 9gix** [comment]
https://github.com/exclusive-gix/cs2102-store/commit/dff1e0eac776ac3f0ac392b529d133837283fda6

https://github.com/exclusive-gix/cs2102-store/blob/dff1e0eac776ac3f0ac392b529d133837283fda6/docs/erd.svg
